### ISSUE TITLE
Delay publishing to Maven

### ISSUE THREAD

**Issue by stianst** [keycloak-rel-testing/keycloak-rel#25]
Publishing to Maven repository during a workflow is not ideal for the following reasons:

* Once published it can't be undone, which is problematic if subsequent steps fail (especially if in a different workflow)
* Deploying to GitHub Packages is super slow, and also very unreliable

A different approach could be to deploy to a local repository, then to upload this somewhere (GH release?) during the workflows, then as a final step we would publish from this local repository to Sonatype. For testing fork we may skip the publishing step altogether.

This would require a bit of re-thinking how we get artifacts from one workflow into another. For example keycloak requires admin-ui, and operator requires keycloak. At the moment this is done by just fetching them from the "release repository".

**Comment by ASzc** [comment]
I had a look around, there's the [deployAtEnd](https://maven.apache.org/plugins/maven-deploy-plugin/deploy-mojo.html#deployAtEnd) option for the standard deploy plugin, but I don't think it's a great fit, since it won't work with separated testing stages.

[deferring-maven-plugin](https://github.com/MeyerNils/deferring-maven-plugin) claims to do what you want, i.e. run deploy later. It seems fairly obscure though, so maybe it would turn out to be unsuitable. Needs checking out

As far as sharing the local repository between jobs, the official documentation suggests [actions/upload-artifact](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts#passing-data-between-jobs-in-a-workflow). This has the limitation of only working between jobs in a single workflow, but supports binaries and has configurable retention periods.

**Comment by jonkoops** [comment]
We've been using the Github CLI to [create releases](https://cli.github.com/manual/gh_release) for the artifacts, as they can be cached between workflows. I have some work under #33 to make the releases process a bit more fleshed out.

**Comment by stianst** [comment]
> I had a look around, there's the [deployAtEnd](https://maven.apache.org/plugins/maven-deploy-plugin/deploy-mojo.html#deployAtEnd) option for the standard deploy plugin, but I don't think it's a great fit, since it won't work with separated testing stages.
> 
> [deferring-maven-plugin](https://github.com/MeyerNils/deferring-maven-plugin) claims to do what you want, i.e. run deploy later. It seems fairly obscure though, so maybe it would turn out to be unsuitable. Needs checking out
> 
> As far as sharing the local repository between jobs, the official documentation suggests [actions/upload-artifact](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts#passing-data-between-jobs-in-a-workflow). This has the limitation of only working between jobs in a single workflow, but supports binaries and has configurable retention periods.

Nexus plugin has [deferred deploy](https://github.com/sonatype/nexus-maven-plugins/blob/main/staging/maven-plugin/README.md#deferred-deploy). That may be useful, but wouldn't work with GH packages though.

Was thinking perhaps this flow could work, but we just wouldn't publish in the test fork. It's a bit of a trade-off, but think it works.

**Comment by stianst** [comment]
> As far as sharing the local repository between jobs, the official documentation suggests [actions/upload-artifact](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts#passing-data-between-jobs-in-a-workflow). This has the limitation of only working between jobs in a single workflow, but supports binaries and has configurable retention periods.

Was thinking that GH releases are more reliable than using artifacts. I imagine situations where a run fails in the middle, and we need to do some adjustments to the release workflow, or something that results in a new run.

Any real downsides to using GH releases instead of artifacts?

**Comment by ASzc** [comment]
> Was thinking that GH releases are more reliable than using artifacts. I imagine situations where a run fails in the middle, and we need to do some adjustments to the release workflow, or something that results in a new run.
> 
> Any real downsides to using GH releases instead of artifacts?

Using GH releases, I would expect it's more likely to hit some sort of throttling from GitHub, since I doubt that API is intended for high volume that you'd see in this case. Also, we'd need to make something to clean up the releases tab automatically, or it could hit a storage limit.

The [documentation says](https://docs.github.com/en/actions/managing-workflow-runs/re-running-workflows-and-jobs#re-running-failed-jobs-in-a-workflow) that when you resume a workflow from the UI, with the intent to re-run just the failed jobs in a workflow, it will reuse all artifacts from the successful jobs. That seems to fit the scenario you're describing?

**Comment by stianst** [comment]
Moved to https://github.com/keycloak-rel/keycloak-rel/issues/34
